version: "2.1"

services:
  app:
    build: .
    image: sterling-premier-league-mock
    container_name: sterling-premier-league-mock
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    ports:
      - "6060:6060"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
